import { Link } from 'react-router-dom';
import { ArrowLeft, Layers, Type, Image, Database, Palette, Code2, Lightbulb, Settings } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';

const Documentation = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b bg-muted/30">
        <div className="max-w-4xl mx-auto px-6 py-8">
          <Button variant="ghost" asChild className="mb-4">
            <Link to="/">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to App
            </Link>
          </Button>
          <h1 className="text-4xl font-bold mb-2">Bulk Image Generator</h1>
          <p className="text-xl text-muted-foreground">
            Technical Documentation & Architecture Guide
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-8 space-y-8">
        {/* Core Concept */}
        <section>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lightbulb className="h-5 w-5" />
                Core Concept
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                The Bulk Image Generator is a <strong>client-side web application</strong> that creates 
                promotional images by combining customizable templates with event data from a JSON feed. 
                It uses the HTML5 Canvas API for image compositing and localStorage for template persistence.
              </p>
              
              <div className="bg-muted rounded-lg p-4">
                <h4 className="font-medium mb-3">Three-Step Workflow</h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="text-center p-3 bg-background rounded border">
                    <div className="text-2xl font-bold text-primary">1</div>
                    <div className="font-medium">Templates</div>
                    <p className="text-sm text-muted-foreground">
                      Create and customize image templates with text overlays and graphics
                    </p>
                  </div>
                  <div className="text-center p-3 bg-background rounded border">
                    <div className="text-2xl font-bold text-primary">2</div>
                    <div className="font-medium">Events</div>
                    <p className="text-sm text-muted-foreground">
                      Load event data from a JSON feed and select events to generate
                    </p>
                  </div>
                  <div className="text-center p-3 bg-background rounded border">
                    <div className="text-2xl font-bold text-primary">3</div>
                    <div className="font-medium">Generate</div>
                    <p className="text-sm text-muted-foreground">
                      Combine templates with events to produce downloadable PNG images
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-green-500/10 border border-green-500/30 rounded-lg p-4">
                <h4 className="font-medium text-green-700 dark:text-green-400 mb-2">Key Benefits</h4>
                <ul className="list-disc list-inside text-sm space-y-1">
                  <li>No server infrastructure required — runs entirely in the browser</li>
                  <li>No API keys or external services needed</li>
                  <li>Instant preview and feedback during template editing</li>
                  <li>Works offline after initial page load</li>
                </ul>
              </div>
            </CardContent>
          </Card>
        </section>

        <Separator />

        {/* Technical Architecture */}
        <section>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Code2 className="h-5 w-5" />
                Technical Architecture
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <h4 className="font-medium mb-3">Canvas Compositing Pipeline</h4>
                <p className="text-sm text-muted-foreground mb-3">
                  Images are generated by drawing layers in a specific order on an HTML5 Canvas:
                </p>
                <div className="bg-muted rounded-lg p-4 font-mono text-sm space-y-2">
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded bg-primary/20 flex items-center justify-center text-xs">1</span>
                    <span>Baseplate (template background image)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded bg-primary/20 flex items-center justify-center text-xs">2</span>
                    <span>Bottom shadow gradient (optional, for text legibility)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded bg-primary/20 flex items-center justify-center text-xs">3</span>
                    <span>Below-layer overlays (drawn under event image)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded bg-primary/20 flex items-center justify-center text-xs">4</span>
                    <span>Event image (centered, positioned 100px above center)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded bg-primary/20 flex items-center justify-center text-xs">5</span>
                    <span>Above-layer overlays (drawn on top of event image)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded bg-primary/20 flex items-center justify-center text-xs">6</span>
                    <span>Text overlay with word wrapping</span>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-medium mb-3">Data Flow</h4>
                <div className="bg-muted rounded-lg p-4 font-mono text-xs overflow-x-auto">
                  <pre>{`┌──────────────────┐     ┌───────────────────┐     ┌──────────────────┐
│                  │     │                   │     │                  │
│  Event Data      │ ──▶ │  Template Editor  │ ──▶ │  Image Generator │
│  (JSON Feed)     │     │  (Canvas Preview) │     │  (Canvas API)    │
│                  │     │                   │     │                  │
└──────────────────┘     └───────────────────┘     └──────────────────┘
         │                        │                        │
         ▼                        ▼                        ▼
┌──────────────────┐     ┌───────────────────┐     ┌──────────────────┐
│  Event Selector  │     │  Template Storage │     │  Generated PNG   │
│  + Image Cropper │     │  (localStorage)   │     │  Downloads       │
└──────────────────┘     └───────────────────┘     └──────────────────┘`}</pre>
                </div>
              </div>

              <div>
                <h4 className="font-medium mb-3">Key Files</h4>
                <div className="grid gap-2 text-sm">
                  <div className="flex gap-2 p-2 bg-muted rounded">
                    <code className="text-primary">src/hooks/useImageGenerator.ts</code>
                    <span className="text-muted-foreground">— Canvas-based image generation logic</span>
                  </div>
                  <div className="flex gap-2 p-2 bg-muted rounded">
                    <code className="text-primary">src/hooks/useTemplateStorage.ts</code>
                    <span className="text-muted-foreground">— localStorage persistence for templates</span>
                  </div>
                  <div className="flex gap-2 p-2 bg-muted rounded">
                    <code className="text-primary">src/types/imageGenerator.ts</code>
                    <span className="text-muted-foreground">— TypeScript interfaces for all data structures</span>
                  </div>
                  <div className="flex gap-2 p-2 bg-muted rounded">
                    <code className="text-primary">src/components/TemplateCanvas.tsx</code>
                    <span className="text-muted-foreground">— Interactive canvas preview with drag-and-drop</span>
                  </div>
                  <div className="flex gap-2 p-2 bg-muted rounded">
                    <code className="text-primary">src/components/TemplateEditor.tsx</code>
                    <span className="text-muted-foreground">— Main editing UI with text/overlay controls</span>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </section>

        <Separator />

        {/* Key Design Decisions */}
        <section>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Palette className="h-5 w-5" />
                Key Design Decisions
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid gap-4">
                <div className="border rounded-lg p-4">
                  <h4 className="font-medium flex items-center gap-2 mb-2">
                    <Layers className="h-4 w-4" />
                    4:5 and 5:4 Safe Zones
                  </h4>
                  <p className="text-sm text-muted-foreground mb-2">
                    Templates include safe zone visualization for common social media crop ratios:
                  </p>
                  <ul className="list-disc list-inside text-sm space-y-1">
                    <li><strong>4:5 Portrait</strong> — Red sidebars show content that will be cropped on Instagram portrait posts</li>
                    <li><strong>5:4 Landscape</strong> — Orange bottom bar shows content cropped on landscape posts</li>
                    <li>Event image width is calculated as <code>95%</code> of the 4:5 safe zone width</li>
                  </ul>
                </div>

                <div className="border rounded-lg p-4">
                  <h4 className="font-medium flex items-center gap-2 mb-2">
                    <Image className="h-4 w-4" />
                    Event Image Positioning
                  </h4>
                  <ul className="list-disc list-inside text-sm space-y-1">
                    <li>Default aspect ratio: <code>3:2</code> (common for event photography)</li>
                    <li>Horizontal: Centered on canvas</li>
                    <li>Vertical: Positioned <code>100px above</code> vertical center</li>
                    <li>Width: <code>95%</code> of the portrait safe zone width</li>
                  </ul>
                </div>

                <div className="border rounded-lg p-4">
                  <h4 className="font-medium flex items-center gap-2 mb-2">
                    <Type className="h-4 w-4" />
                    Text Rendering
                  </h4>
                  <ul className="list-disc list-inside text-sm space-y-1">
                    <li>Font: Roboto (loaded via Google Fonts, weights 400 and 700)</li>
                    <li>Word wrapping algorithm respects <code>maxWidth</code> constraint</li>
                    <li>Event name can have a separate font size from other fields</li>
                    <li>All text rendered with <code>bold</code> weight by default</li>
                    <li>Line height: <code>1.2×</code> font size</li>
                  </ul>
                </div>

                <div className="border rounded-lg p-4">
                  <h4 className="font-medium flex items-center gap-2 mb-2">
                    <Database className="h-4 w-4" />
                    CORS Proxy
                  </h4>
                  <p className="text-sm text-muted-foreground">
                    External images (event images and JSON feeds) are loaded through <code>corsproxy.io</code> 
                    to bypass cross-origin restrictions. This allows the Canvas API to read pixel data 
                    from external images and export them as PNG files.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </section>

        <Separator />

        {/* Configuration Reference */}
        <section>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Settings className="h-5 w-5" />
                Configuration Reference
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <h4 className="font-medium mb-3">TextConfig Interface</h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b">
                        <th className="text-left py-2 pr-4">Property</th>
                        <th className="text-left py-2 pr-4">Type</th>
                        <th className="text-left py-2 pr-4">Default</th>
                        <th className="text-left py-2">Description</th>
                      </tr>
                    </thead>
                    <tbody className="font-mono text-xs">
                      <tr className="border-b">
                        <td className="py-2 pr-4">fontFamily</td>
                        <td className="py-2 pr-4 text-muted-foreground">string</td>
                        <td className="py-2 pr-4">"Roboto"</td>
                        <td className="py-2 font-sans">Font family for all text</td>
                      </tr>
                      <tr className="border-b">
                        <td className="py-2 pr-4">fontSize</td>
                        <td className="py-2 pr-4 text-muted-foreground">number</td>
                        <td className="py-2 pr-4">56</td>
                        <td className="py-2 font-sans">Base font size in pixels</td>
                      </tr>
                      <tr className="border-b">
                        <td className="py-2 pr-4">eventNameFontSize</td>
                        <td className="py-2 pr-4 text-muted-foreground">number?</td>
                        <td className="py-2 pr-4">56</td>
                        <td className="py-2 font-sans">Separate size for event name (optional)</td>
                      </tr>
                      <tr className="border-b">
                        <td className="py-2 pr-4">color</td>
                        <td className="py-2 pr-4 text-muted-foreground">string</td>
                        <td className="py-2 pr-4">"#ffffff"</td>
                        <td className="py-2 font-sans">Text color (hex)</td>
                      </tr>
                      <tr className="border-b">
                        <td className="py-2 pr-4">x, y</td>
                        <td className="py-2 pr-4 text-muted-foreground">number</td>
                        <td className="py-2 pr-4">540, 940</td>
                        <td className="py-2 font-sans">Text position in pixels</td>
                      </tr>
                      <tr className="border-b">
                        <td className="py-2 pr-4">maxWidth</td>
                        <td className="py-2 pr-4 text-muted-foreground">number</td>
                        <td className="py-2 pr-4">550</td>
                        <td className="py-2 font-sans">Max width before word wrap</td>
                      </tr>
                      <tr className="border-b">
                        <td className="py-2 pr-4">textAlign</td>
                        <td className="py-2 pr-4 text-muted-foreground">"left" | "center" | "right"</td>
                        <td className="py-2 pr-4">"center"</td>
                        <td className="py-2 font-sans">Horizontal text alignment</td>
                      </tr>
                      <tr className="border-b">
                        <td className="py-2 pr-4">bottomShadowEnabled</td>
                        <td className="py-2 pr-4 text-muted-foreground">boolean?</td>
                        <td className="py-2 pr-4">false</td>
                        <td className="py-2 font-sans">Enable gradient shadow at bottom</td>
                      </tr>
                      <tr>
                        <td className="py-2 pr-4">bottomShadowOpacity</td>
                        <td className="py-2 pr-4 text-muted-foreground">number?</td>
                        <td className="py-2 pr-4">0.5</td>
                        <td className="py-2 font-sans">Shadow opacity (0-1)</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <div>
                <h4 className="font-medium mb-3">Date Format Examples</h4>
                <div className="grid grid-cols-3 gap-2 text-sm">
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">short</div>
                    <code>15 Jan</code>
                  </div>
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">long</div>
                    <code>15 January 2025</code>
                  </div>
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">full</div>
                    <code>Friday, 15 January 2025</code>
                  </div>
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">with ordinal</div>
                    <code>15th January 2025</code>
                  </div>
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">with uppercase</div>
                    <code>15 JANUARY 2025</code>
                  </div>
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">short + ordinal</div>
                    <code>15th Jan</code>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-medium mb-3">Location Format Examples</h4>
                <div className="grid grid-cols-3 gap-2 text-sm">
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">city</div>
                    <code>Austin</code>
                  </div>
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">city-state</div>
                    <code>Austin, TX</code>
                  </div>
                  <div className="p-2 bg-muted rounded">
                    <div className="text-xs text-muted-foreground mb-1">city-country</div>
                    <code>Austin, USA</code>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-medium mb-3">Overlay Layer Behavior</h4>
                <div className="grid gap-2 text-sm">
                  <div className="p-3 bg-muted rounded flex items-center gap-3">
                    <span className="font-mono text-primary">below</span>
                    <span className="text-muted-foreground">→</span>
                    <span>Drawn under the event image (e.g., decorative backgrounds)</span>
                  </div>
                  <div className="p-3 bg-muted rounded flex items-center gap-3">
                    <span className="font-mono text-primary">above</span>
                    <span className="text-muted-foreground">→</span>
                    <span>Drawn on top of the event image (e.g., logos, frames)</span>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </section>

        <Separator />

        {/* Future Enhancements */}
        <section>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lightbulb className="h-5 w-5" />
                Future Enhancement Ideas
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm">
                <li className="flex items-start gap-2">
                  <span className="text-primary">•</span>
                  <span><strong>Configurable event image sizing</strong> — Allow adjusting width percentage and Y offset per template</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary">•</span>
                  <span><strong>Template import/export</strong> — Save and share templates as JSON files</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary">•</span>
                  <span><strong>Server-side rendering</strong> — Integrate with Placid API for advanced features</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary">•</span>
                  <span><strong>Custom fonts</strong> — Upload and use custom font files</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary">•</span>
                  <span><strong>Batch download</strong> — Download all generated images as a ZIP file</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary">•</span>
                  <span><strong>Multiple aspect ratio outputs</strong> — Generate 1:1, 4:5, and 16:9 versions simultaneously</span>
                </li>
              </ul>
            </CardContent>
          </Card>
        </section>

        {/* Footer */}
        <div className="text-center py-8 text-sm text-muted-foreground">
          <p>Built with React, TypeScript, Tailwind CSS, and the HTML5 Canvas API</p>
          <Button variant="link" asChild className="mt-2">
            <Link to="/">← Return to Application</Link>
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Documentation;
